In [ ]:
pip install selenium

Collecting selenium
  Downloading selenium-4.15.2-py3-none-any.whl (10.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 53.0 MB/s eta 0:00:00
Requirement already satisfied: urllib3[socks]<3,>=1.26 in /usr/local/lib/python3.10/dist-packages (from selenium) (2.0.7)
Collecting trio~=0.17 (from selenium)
  Downloading trio-0.23.1-py3-none-any.whl (448 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 448.3/448.3 kB 34.5 MB/s eta 0:00:00
Collecting trio-websocket~=0.9 (from selenium)
  Downloading trio_websocket-0.11.1-py3-none-any.whl (17 kB)
Requirement already satisfied: certifi>=2021.10.8 in /usr/local/lib/python3.10/dist-packages (from selenium) (2023.7.22)
Requirement already satisfied: attrs>=20.1.0 in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (23.1.0)
Requirement already satisfied: sortedcontainers in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (3.4)
Collecting outcome (from trio~=0.17->selenium)
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: sniffio>=1.3.0 in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (1.3.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in /usr/local/lib/python3.10/dist-packages (from trio~=0.17->selenium) (1.1.3)
Collecting wsproto>=0.14 (from trio-websocket~=0.9->selenium)
  Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Requirement already satisfied: pysocks!=1.5.7,<2.0,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Collecting h11<1,>=0.9.0 (from wsproto>=0.14->trio-websocket~=0.9->selenium)
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 6.1 MB/s eta 0:00:00
Installing collected packages: outcome, h11, wsproto, trio, trio-websocket, selenium
Successfully installed h11-0.14.0 outcome-1.3.0.post0 selenium-4.15.2 trio-0.23.1 trio-websocket-0.11.1 wsproto-1.2.0

In [ ]:
pip install requests-html

Collecting requests-html
  Downloading requests_html-0.10.0-py3-none-any.whl (13 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from requests-html) (2.31.0)
Collecting pyquery (from requests-html)
  Downloading pyquery-2.0.0-py3-none-any.whl (22 kB)
Collecting fake-useragent (from requests-html)
  Downloading fake_useragent-1.3.0-py3-none-any.whl (15 kB)
Collecting parse (from requests-html)
  Downloading parse-1.19.1-py2.py3-none-any.whl (18 kB)
Collecting bs4 (from requests-html)
  Downloading bs4-0.0.1.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... done
Collecting w3lib (from requests-html)
  Downloading w3lib-2.1.2-py3-none-any.whl (21 kB)
Collecting pyppeteer>=0.0.14 (from requests-html)
  Downloading pyppeteer-1.0.2-py3-none-any.whl (83 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.4/83.4 kB 4.2 MB/s eta 0:00:00
Requirement already satisfied: appdirs<2.0.0,>=1.4.3 in /usr/local/lib/python3.10/dist-packages (from pyppeteer>=0.0.14->requests-html) (1.4.4)
Requirement already satisfied: certifi>=2021 in /usr/local/lib/python3.10/dist-packages (from pyppeteer>=0.0.14->requests-html) (2023.7.22)
Requirement already satisfied: importlib-metadata>=1.4 in /usr/local/lib/python3.10/dist-packages (from pyppeteer>=0.0.14->requests-html) (6.8.0)
Collecting pyee<9.0.0,>=8.1.0 (from pyppeteer>=0.0.14->requests-html)
  Downloading pyee-8.2.2-py2.py3-none-any.whl (12 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.42.1 in /usr/local/lib/python3.10/dist-packages (from pyppeteer>=0.0.14->requests-html) (4.66.1)
Collecting urllib3<2.0.0,>=1.25.8 (from pyppeteer>=0.0.14->requests-html)
  Downloading urllib3-1.26.18-py2.py3-none-any.whl (143 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.8/143.8 kB 8.9 MB/s eta 0:00:00
Collecting websockets<11.0,>=10.0 (from pyppeteer>=0.0.14->requests-html)
  Downloading websockets-10.4-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (106 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.8/106.8 kB 13.3 MB/s eta 0:00:00
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from bs4->requests-html) (4.11.2)
Requirement already satisfied: lxml>=2.1 in /usr/local/lib/python3.10/dist-packages (from pyquery->requests-html) (4.9.3)
Collecting cssselect>=1.2.0 (from pyquery->requests-html)
  Downloading cssselect-1.2.0-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->requests-html) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->requests-html) (3.4)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.10/dist-packages (from importlib-metadata>=1.4->pyppeteer>=0.0.14->requests-html) (3.17.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->bs4->requests-html) (2.5)
Building wheels for collected packages: bs4
  Building wheel for bs4 (setup.py) ... done
  Created wheel for bs4: filename=bs4-0.0.1-py3-none-any.whl size=1257 sha256=bfc40e70354d0658d7d17c41a9069bf69c7295c1763ddee9785da72917b86914
  Stored in directory: /root/.cache/pip/wheels/25/42/45/b773edc52acb16cd2db4cf1a0b47117e2f69bb4eb300ed0e70
Successfully built bs4
Installing collected packages: pyee, parse, fake-useragent, websockets, w3lib, urllib3, cssselect, pyquery, pyppeteer, bs4, requests-html
  Attempting uninstall: urllib3
    Found existing installation: urllib3 2.0.7
    Uninstalling urllib3-2.0.7:
      Successfully uninstalled urllib3-2.0.7
Successfully installed bs4-0.0.1 cssselect-1.2.0 fake-useragent-1.3.0 parse-1.19.1 pyee-8.2.2 pyppeteer-1.0.2 pyquery-2.0.0 requests-html-0.10.0 urllib3-1.26.18 w3lib-2.1.2 websockets-10.4

***THE FOLLOWING DATA REPRESENTS THE INFORMATION OF THE WORLDCUPS HELD TILL 2023***

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.cricketworldcup.com/stats/players/most-wickets"

response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

# Assuming the relevant data is in a table, find the table
table = soup.find('table')

# Initialize lists to store data
player_names = []
teams = []
wickets = []

# Extract data from the table
for row in table.find_all('tr', class_='js-row'):
    columns = row.find_all('td')

    # Extract player name
    player_name_parts = [span.text.strip() for span in columns[1].find_all('span')] if columns[1] else []
    player_name = " ".join(player_name_parts) if player_name_parts else "N/A"
    player_names.append(player_name)

    # Extract team
    team = columns[2].text.strip() if columns[2] else "N/A"
    teams.append(team)

    # Extract main statistics (Wickets)
    main_stat = columns[6].text.strip() if columns[6] else "N/A"
    wickets.append(main_stat.split("\n")[1] if "\n" in main_stat else "N/A")

# Create a Pandas DataFrame
data = {'Player': player_names, 'Team': teams, 'Wickets': wickets}
df = pd.DataFrame(data)

# Display the DataFrame
print(df)

                  Player Team Wickets
0          Glenn McGrath  AUS      71
1   Muttiah Muralitharan   SL      68
2         Mitchell Starc  AUS      59
3         Lasith Malinga   SL      56
4            Wasim Akram  PAK      55
5            Trent Boult   NZ      52
6          Chaminda Vaas   SL      49
7         Mohammad Shami  IND      47
8            Zaheer Khan  IND      44
9        Javagal Srinath  IND      44
10       Shakib Al Hasan  BAN      43
11           Imran Tahir   SA      40
12          Allan Donald   SA      38
13           Tim Southee   NZ      38
14        Daniel Vettori   NZ      36
15            Jacob Oram   NZ      36
16            Wahab Riaz  PAK      35
17        Jasprit Bumrah  IND      35
18             Brett Lee  AUS      35
19            Imran Khan  PAK      34
20            Shaun Tait  AUS      34
21             Brad Hogg  AUS      34
22        Shaheen Afridi  PAK      34
23          Chris Harris   NZ      32
24           Shane Warne  AUS      32

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.cricketworldcup.com/stats/players/best-bowling-average"

response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

# Assuming the relevant data is in a table, find the table
table = soup.find('table')

# Initialize lists to store data
player_names = []
teams = []
best_bowling_averages = []

# Extract data from the table
for row in table.find_all('tr', class_='js-row'):
    columns = row.find_all('td')

    # Extract player name
    player_name_parts = [span.text.strip() for span in columns[1].find_all('span')] if columns[1] else []
    player_name = " ".join(player_name_parts) if player_name_parts else "N/A"
    player_names.append(player_name)

    # Extract team
    team = columns[2].text.strip() if columns[2] else "N/A"
    teams.append(team)

    # Extract main statistics (Best Bowling Average)
    best_bowling_average = columns[6].text.strip().split('\n')[1] if columns[6] else "N/A"
    best_bowling_averages.append(float(best_bowling_average) if '.' in best_bowling_average else "N/A")

# Create a Pandas DataFrame
data = {'Player': player_names, 'Team': teams, 'Best Bowling Average': best_bowling_averages}
df_best_bowling = pd.DataFrame(data)

# Display the DataFrame
print(df_best_bowling)

               Player Team  Best Bowling Average
0         Andy Bichel  AUS                 12.31
1      Vasbert Drakes   WI                 13.00
2      Mohammad Shami  IND                 13.61
3    Michael Hendrick  ENG                 14.90
4           Chris Old  ENG                 15.18
5      Nathan Bracken  AUS                 16.12
6        Geoff Allott   NZ                 16.25
7     Michael Holding   WI                 17.05
8          Shane Bond   NZ                 17.26
9          Bob Willis  ENG                 17.50
10     Bernard Julien   WI                 17.70
11        Umesh Yadav  IND                 17.83
12          Brett Lee  AUS                 17.97
13          Andre Nel   SA                 18.08
14      Glenn McGrath  AUS                 18.19
15     Jasprit Bumrah  IND                 18.20
16        Keith Boyce   WI                 18.50
17  Patrick Patterson   WI                 18.53
18          Vic Marks  ENG                 18.92
19           Umar Gul  PAK                 19.11
20     Richard Hadlee   NZ                 19.13
21          Brad Hogg  AUS                 19.23
22         Imran Khan  PAK                 19.26
23          Madan Lal  IND                 19.36
24     Gerald Coetzee   SA                 19.38

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.cricketworldcup.com/stats/players/best-bowling-strike-rate-innings"

response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

# Assuming the relevant data is in a table, find the table
table = soup.find('table')

# Initialize lists to store data
player_names = []
teams = []
best_bowling_strike_rates = []

# Extract data from the table
for row in table.find_all('tr', class_='js-row'):
    columns = row.find_all('td')

    # Extract player name
    player_name_parts = [span.text.strip() for span in columns[1].find_all('span')] if columns[1] else []
    player_name = " ".join(player_name_parts) if player_name_parts else "N/A"
    player_names.append(player_name)

    # Extract team
    team = columns[2].text.strip() if columns[2] else "N/A"
    teams.append(team)

    # Extract main statistics (Best Bowling Strike Rate)
    best_bowling_strike_rate = columns[6].text.strip().split('\n')[1] if columns[6] else "N/A"
    best_bowling_strike_rates.append(float(best_bowling_strike_rate) if '.' in best_bowling_strike_rate else "N/A")

# Create a Pandas DataFrame
data = {'Player': player_names, 'Team': teams, 'Best Bowling Strike Rate': best_bowling_strike_rates}
df_best_strike_rate = pd.DataFrame(data)

# Display the DataFrame
print(df_best_strike_rate)

                  Player Team  Best Bowling Strike Rate
0            Andy Bichel  AUS                      3.00
1             Adam Zampa  AUS                      4.50
2   Tillakaratne Dilshan   SL                      4.50
3         Reon Dane King   WI                      4.50
4           Chris Harris   NZ                      4.75
5             Jacob Oram   NZ                      5.66
6            Steve Waugh  AUS                      6.00
7         Daan van Bunge  NED                      6.00
8       Dilhara Fernando   SL                      6.00
9         Mohammad Shami  IND                      6.00
10         Grant Elliott   NZ                      6.00
11         Jeevan Mendis   SL                      6.00
12         Glenn McGrath  AUS                      6.00
13        Andrew Symonds  AUS                      6.00
14          Steve Tikolo  KEN                      6.50
15          Yuvraj Singh  IND                      6.75
16        Mitchell Starc  AUS                      7.00
17             Brad Hogg  AUS                      7.25
18  Muttiah Muralitharan   SL                      7.50
19        Hamish Bennett   NZ                      7.50
20   Mohammad Azharuddin  IND                      7.66
21        Lasith Malinga   SL                      7.66
22           Tim Southee   NZ                      7.71
23     Khan Abdur Razzak  BAN                      8.00
24         Shahid Afridi  PAK                      8.00

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.cricketworldcup.com/stats/players/best-bowling-economy-innings"

response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

# Assuming the relevant data is in a table, find the table
table = soup.find('table')

# Initialize lists to store data
player_names = []
teams = []
best_bowling_economies = []

# Extract data from the table
for row in table.find_all('tr', class_='js-row'):
    columns = row.find_all('td')

    # Extract player name
    player_name_parts = [span.text.strip() for span in columns[1].find_all('span')] if columns[1] else []
    player_name = " ".join(player_name_parts) if player_name_parts else "N/A"
    player_names.append(player_name)

    # Extract team
    team = columns[2].text.strip() if columns[2] else "N/A"
    teams.append(team)

    # Extract main statistics (Best Bowling Economy)
    best_bowling_economy = columns[6].text.strip().split('\n')[1] if columns[6] else "N/A"
    best_bowling_economies.append(float(best_bowling_economy) if '.' in best_bowling_economy else "N/A")

# Create a Pandas DataFrame
data = {'Player': player_names, 'Team': teams, 'Best Bowling Economy': best_bowling_economies}
df_best_economy = pd.DataFrame(data)

# Display the DataFrame
print(df_best_economy)

                  Player Team  Best Bowling Economy
0           Dermot Reeve  ENG                  0.40
1        Geoffrey Miller  ENG                  0.50
2            Bishan Bedi  IND                  0.50
3       Michael Hendrick  ENG                  0.62
4            Andre Botha  IRE                  0.62
5         Mohammad Irfan  PAK                  0.66
6           Phil Simmons   WI                  0.66
7          Shaun Pollock   SA                  0.68
8             Jacob Oram   NZ                  0.70
9             Kyle Mills   NZ                  0.75
10             Chris Old  ENG                  0.80
11            Barry Wood  ENG                  0.80
12        Curtly Ambrose   WI                  0.80
13        Richard Hadlee   NZ                  0.83
14           Aasif Karim  KEN                  0.84
15  Somachandra de Silva   SL                  0.91
16             John Snow  ENG                  0.91
17          Steve Tikolo  KEN                  0.92
18  Tillakaratne Dilshan   SL                  0.92
19         Derek Pringle  ENG                  0.96
20            Majid Khan  PAK                  1.00
21         Hansie Cronje   SA                  1.00
22         Wayne Parnell   SA                  1.00
23            Bob Willis  ENG                  1.00
24        Courtney Walsh   WI                  1.00

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.cricketworldcup.com/stats/players/most-maidens"

response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

# Assuming the relevant data is in a table, find the table
table = soup.find('table')

# Initialize lists to store data
player_names = []
teams = []
most_maidens = []

# Extract data from the table
for row in table.find_all('tr', class_='js-row'):
    columns = row.find_all('td')

    # Extract player name
    player_name_parts = [span.text.strip() for span in columns[1].find_all('span')] if columns[1] else []
    player_name = " ".join(player_name_parts) if player_name_parts else "N/A"
    player_names.append(player_name)

    # Extract team
    team = columns[2].text.strip() if columns[2] else "N/A"
    teams.append(team)

    # Extract main statistics (Most Maidens)
    most_maiden = columns[6].find('span', class_='stats-table__main-stat-container').text.strip() if columns[6] else "N/A"
    most_maidens.append(int(most_maiden) if most_maiden.isdigit() else "N/A")

# Create a Pandas DataFrame
data = {'Player': player_names, 'Team': teams, 'Most Maidens': most_maidens}
df_most_maidens = pd.DataFrame(data)

# Display the DataFrame
print(df_most_maidens)

               Player Team  Most Maidens
0       Glenn McGrath  AUS            42
1       Chaminda Vaas   SL            39
2      Richard Hadlee   NZ            38
3       Shaun Pollock   SA            37
4          Ian Botham  ENG            33
5   Phillip DeFreitas  ENG            30
6        Andy Roberts   WI            29
7          Bob Willis  ENG            27
8           Kapil Dev  IND            27
9         Trent Boult   NZ            24
10     Courtney Walsh   WI            23
11         Shane Bond   NZ            21
12    Javagal Srinath  IND            21
13         Jacob Oram   NZ            21
14     Curtly Ambrose   WI            20
15          Chris Old  ENG            18
16         Imran Khan  PAK            18
17        Bishan Bedi  IND            17
18        Wasim Akram  PAK            17
19       Lance Cairns   NZ            16
20     Ewen Chatfield   NZ            16
21    Michael Holding   WI            16
22        Shane Warne  AUS            16
23        Tim Southee   NZ            16
24        Martin Suji  KEN            16

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.cricketworldcup.com/stats/players/most-dot-balls"

response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

# Assuming the relevant data is in a table, find the table
table = soup.find('table')

# Initialize lists to store data
player_names = []
teams = []
most_dot_balls = []

# Extract data from the table
for row in table.find_all('tr', class_='js-row'):
    columns = row.find_all('td')

    # Extract player name
    player_name_parts = [span.text.strip() for span in columns[1].find_all('span')] if columns[1] else []
    player_name = " ".join(player_name_parts) if player_name_parts else "N/A"
    player_names.append(player_name)

    # Extract team
    team = columns[2].text.strip() if columns[2] else "N/A"
    teams.append(team)

    # Extract main statistics (Most Dot Balls)
    most_dot_ball = columns[6].find('span', class_='stats-table__main-stat-container').text.strip() if columns[6] else "N/A"
    most_dot_balls.append(int(most_dot_ball) if most_dot_ball.isdigit() else "N/A")

# Create a Pandas DataFrame
data = {'Player': player_names, 'Team': teams, 'Most Dot Balls': most_dot_balls}
df_most_dot_balls = pd.DataFrame(data)

# Display the DataFrame
print(df_most_dot_balls)

                  Player Team  Most Dot Balls
0            Trent Boult   NZ             973
1        Shakib Al Hasan  BAN             858
2         Mitchell Starc  AUS             794
3         Lasith Malinga   SL             788
4         Daniel Vettori   NZ             702
5            Tim Southee   NZ             652
6            Imran Tahir   SA             614
7           Chris Woakes  ENG             605
8         Jasprit Bumrah  IND             597
9       Mashrafe Mortaza  BAN             590
10           Pat Cummins  AUS             577
11        James Anderson  ENG             560
12         Mohammad Nabi  AFG             553
13       Ravindra Jadeja  IND             530
14  Muttiah Muralitharan   SL             526
15            Wahab Riaz  PAK             521
16         Kagiso Rabada   SA             517
17            Shaun Tait  AUS             512
18           Rashid Khan  AFG             487
19        Mohammad Shami  IND             480
20       Lockie Ferguson   NZ             479
21      Mitchell Johnson  AUS             468
22           Adil Rashid  ENG             459
23         Mitch Santner   NZ             458
24      Mujeeb Ur Rahman  AFG             452

In [ ]:
# Merge Most Wickets and Best Bowling Average DataFrames
merged_df = pd.merge(df, df_best_bowling, on=['Player', 'Team'], how='outer')

# Merge with Best Bowling Strike Rate DataFrame
merged_df = pd.merge(merged_df, df_best_strike_rate, on=['Player', 'Team'], how='outer')

# Merge with Best Bowling Economy DataFrame
merged_df = pd.merge(merged_df, df_best_economy, on=['Player', 'Team'], how='outer')

# Merge with Most Maidens DataFrame
merged_df = pd.merge(merged_df, df_most_maidens, on=['Player', 'Team'], how='outer')

# Merge with Most Dot Balls DataFrame
merged_df = pd.merge(merged_df, df_most_dot_balls, on=['Player', 'Team'], how='outer')

# Display the final merged DataFrame
print(merged_df)

                  Player Team Wickets  Best Bowling Average  \
0          Glenn McGrath  AUS      71                 18.19
1   Muttiah Muralitharan   SL      68                   NaN
2         Mitchell Starc  AUS      59                   NaN
3         Lasith Malinga   SL      56                   NaN
4            Wasim Akram  PAK      55                   NaN
..                   ...  ...     ...                   ...
92       Lockie Ferguson   NZ     NaN                   NaN
93      Mitchell Johnson  AUS     NaN                   NaN
94           Adil Rashid  ENG     NaN                   NaN
95         Mitch Santner   NZ     NaN                   NaN
96      Mujeeb Ur Rahman  AFG     NaN                   NaN

    Best Bowling Strike Rate  Best Bowling Economy  Most Maidens  \
0                       6.00                   NaN          42.0
1                       7.50                   NaN           NaN
2                       7.00                   NaN           NaN
3                       7.66                   NaN           NaN
4                        NaN                   NaN          17.0
..                       ...                   ...           ...
92                       NaN                   NaN           NaN
93                       NaN                   NaN           NaN
94                       NaN                   NaN           NaN
95                       NaN                   NaN           NaN
96                       NaN                   NaN           NaN

    Most Dot Balls
0              NaN
1            526.0
2            794.0
3            788.0
4              NaN
..             ...
92           479.0
93           468.0
94           459.0
95           458.0
96           452.0

[97 rows x 8 columns]

In [ ]:
merged_df.head()

,Player,Team,Wickets,Best Bowling Average,Best Bowling Strike Rate,Best Bowling Economy,Most Maidens,Most Dot Balls
0,Glenn McGrath,AUS,71,18.19,6.00,NaN,42.0,NaN
1,Muttiah Muralitharan,SL,68,NaN,7.50,NaN,NaN,526.0
2,Mitchell Starc,AUS,59,NaN,7.00,NaN,NaN,794.0
3,Lasith Malinga,SL,56,NaN,7.66,NaN,NaN,788.0
4,Wasim Akram,PAK,55,NaN,NaN,NaN,17.0,NaN

In [ ]:
merged_df.tail()

,Player,Team,Wickets,Best Bowling Average,Best Bowling Strike Rate,Best Bowling Economy,Most Maidens,Most Dot Balls
92,Lockie Ferguson,NZ,NaN,NaN,NaN,NaN,NaN,479.0
93,Mitchell Johnson,AUS,NaN,NaN,NaN,NaN,NaN,468.0
94,Adil Rashid,ENG,NaN,NaN,NaN,NaN,NaN,459.0
95,Mitch Santner,NZ,NaN,NaN,NaN,NaN,NaN,458.0
96,Mujeeb Ur Rahman,AFG,NaN,NaN,NaN,NaN,NaN,452.0

In [ ]:
# Assuming merged_df is the merged DataFrame
merged_df.to_csv('cricket_stats_merged.csv', index=False)

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://sportstar.thehindu.com/cricket/icc-cricket-world-cup/most-wickets-odi-world-cup-2023-full-list-highest-wicket-takers-stats-records/article67527642.ece"

response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

# Find the table containing the most wickets data
table = soup.find('table', class_='table')
if table:
    # Initialize lists to store data
    player_names = []
    matches = []
    wickets = []
    economy = []
    average = []
    bbi = []

    # Extract data from the table
    for row in table.find_all('tr')[1:]:
        columns = row.find_all('td')
        player_name = columns[0].text.strip().split('(')[0]
        match = int(columns[1].text.strip())
        wicket = int(columns[2].text.strip())
        economy_value = float(columns[3].text.strip())
        average_value = float(columns[4].text.strip())
        bbi_value = columns[5].text.strip()

        player_names.append(player_name)
        matches.append(match)
        wickets.append(wicket)
        economy.append(economy_value)
        average.append(average_value)
        bbi.append(bbi_value)

    # Create a Pandas DataFrame
    data = {
        'Bowler': player_names,
        'Mat': matches,
        'Wickets': wickets,
        'Economy': economy,
        'Average': average,
        'BBI': bbi
    }
    df_most_wickets = pd.DataFrame(data)

    # Display the DataFrame
    print(df_most_wickets)
else:
    print("Table not found on the webpage.")

                Bowler  Mat  Wickets  Economy  Average   BBI
0          Adam Zampa     9       22     5.26    18.90   4/8
1  Dilshan Madushanka     9       21     6.70    25.00  5/80
2      Gerald Coetzee     7       18     6.40    19.38  4/44
3      Shaheen Afridi     9       18     5.93    26.72  5/54
4      Jasprit Bumrah     9       17     3.65    15.64  4/39
5        Marco Jansen     8       17     6.41    24.41  3/31
6      Mohammed Shami     5       16     4.78     9.56  5/18
7     Ravindra Jadeja     9       16     3.97    18.25  5/33
8    Mitchell Santner     9       16     4.81    24.87  5/59
9        Bas de Leede     9       16     7.26    30.43  4/62

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://sportstar.thehindu.com/cricket/icc-cricket-world-cup/most-wickets-odi-world-cup-2023-full-list-highest-wicket-takers-stats-records/article67527642.ece"

response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

# Find the table containing the most wickets data
table = soup.find('table', class_='table')
if table:
    # Initialize lists to store data
    player_names = []
    teams = []
    matches = []
    wickets = []
    economy = []
    average = []
    bbi = []

    # Extract data from the table
    for row in table.find_all('tr')[1:]:
        columns = row.find_all('td')
        player_name = columns[0].text.strip().split('(')[0]
        team = columns[0].text.strip().split('(')[1].replace(')', '')  # Extract team from the parentheses
        match = int(columns[1].text.strip())
        wicket = int(columns[2].text.strip())
        economy_value = float(columns[3].text.strip())
        average_value = float(columns[4].text.strip())
        bbi_value = columns[5].text.strip()

        player_names.append(player_name)
        teams.append(team)
        matches.append(match)
        wickets.append(wicket)
        economy.append(economy_value)
        average.append(average_value)
        bbi.append(bbi_value)

    # Create a Pandas DataFrame
    data = {
        'Bowler': player_names,
        'Team': teams,
        'Mat': matches,
        'Wickets': wickets,
        'Economy': economy,
        'Average': average,
        'BBI': bbi
    }
    df_most_wickets = pd.DataFrame(data)

    # Display the DataFrame
    print(df_most_wickets)
else:
    print("Table not found on the webpage.")

                Bowler Team  Mat  Wickets  Economy  Average   BBI
0          Adam Zampa   AUS    9       22     5.26    18.90   4/8
1  Dilshan Madushanka    SL    9       21     6.70    25.00  5/80
2      Gerald Coetzee    SA    7       18     6.40    19.38  4/44
3      Shaheen Afridi   PAK    9       18     5.93    26.72  5/54
4      Jasprit Bumrah   IND    9       17     3.65    15.64  4/39
5        Marco Jansen    SA    8       17     6.41    24.41  3/31
6      Mohammed Shami   IND    5       16     4.78     9.56  5/18
7     Ravindra Jadeja   IND    9       16     3.97    18.25  5/33
8    Mitchell Santner    NZ    9       16     4.81    24.87  5/59
9        Bas de Leede   NED    9       16     7.26    30.43  4/62

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://sportstar.thehindu.com/cricket/icc-cricket-world-cup/most-wickets-odi-world-cup-2023-full-list-highest-wicket-takers-stats-records/article67527642.ece"

response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

# Find the table containing the most wickets data
table = soup.find('table', class_='table')
if table:
    # Initialize lists to store data
    player_names = []
    teams = []
    matches = []
    wickets = []
    economy = []
    average = []
    bbi = []

    # Extract data from the table
    for row in table.find_all('tr')[1:]:
        columns = row.find_all('td')
        player_name = columns[0].text.strip().split('(')[0]
        team = columns[0].text.strip().split('(')[1].replace(')', '')  # Extract team from the parentheses
        match = int(columns[1].text.strip())
        wicket = int(columns[2].text.strip())
        economy_value = float(columns[3].text.strip())
        average_value = float(columns[4].text.strip())
        bbi_value = columns[5].text.strip()

        player_names.append(player_name)
        teams.append(team)
        matches.append(match)
        wickets.append(wicket)
        economy.append(economy_value)
        average.append(average_value)
        bbi.append(bbi_value)

    # Create a Pandas DataFrame
    data = {
        'Bowler': player_names,
        'Team': teams,
        'Mat': matches,
        'Wickets': wickets,
        'Economy': economy,
        'Average': average,
        'BBI': bbi
    }
    df_most_wickets = pd.DataFrame(data)

    # Filter players from the semifinal teams (SA, NZ, IND, AUS)
    semifinal_teams = ['SA', 'NZ', 'IND', 'AUS']
    df_semifinal_players = df_most_wickets[df_most_wickets['Team'].isin(semifinal_teams)]

    # Display the DataFrame with players from the semifinal teams
    print(df_semifinal_players)
else:
    print("Table not found on the webpage.")

              Bowler Team  Mat  Wickets  Economy  Average   BBI
0        Adam Zampa   AUS    9       22     5.26    18.90   4/8
2    Gerald Coetzee    SA    7       18     6.40    19.38  4/44
4    Jasprit Bumrah   IND    9       17     3.65    15.64  4/39
5      Marco Jansen    SA    8       17     6.41    24.41  3/31
6    Mohammed Shami   IND    5       16     4.78     9.56  5/18
7   Ravindra Jadeja   IND    9       16     3.97    18.25  5/33
8  Mitchell Santner    NZ    9       16     4.81    24.87  5/59

In [ ]:
df_semifinal_players.to_csv('semifinal_players.csv', index=False)

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.espncricinfo.com/records/tournament/bowling-most-wickets-career/icc-cricket-world-cup-2023-24-15338"

response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

# Find the table containing the most wickets data
table = soup.find('table', class_='ds-table-xs')  # Update the class name based on the actual class of the table
if table:
    # Initialize lists to store data
    player_names = []
    matches = []
    innings = []
    balls = []
    overs = []
    maidens = []
    runs = []
    wickets = []
    bbi = []
    average = []
    economy = []
    strike_rate = []

    # Extract data from the table
    for row in table.find('tbody').find_all('tr'):
        columns = row.find_all('td')
        player_name = columns[0].text.strip()
        match = int(columns[2].text.strip())
        inning = int(columns[3].text.strip())
        ball = int(columns[4].text.strip())
        over = float(columns[5].text.strip())
        maiden = None if columns[6].text.strip() == '-' else int(columns[6].text.strip())
        run = int(columns[7].text.strip())
        wicket = int(columns[8].text.strip())
        bbi_value = columns[9].text.strip()
        average_value = float(columns[10].text.strip())
        economy_value = float(columns[11].text.strip())
        strike_rate_value = float(columns[12].text.strip())

        player_names.append(player_name)
        matches.append(match)
        innings.append(inning)
        balls.append(ball)
        overs.append(over)
        maidens.append(maiden)
        runs.append(run)
        wickets.append(wicket)
        bbi.append(bbi_value)
        average.append(average_value)
        economy.append(economy_value)
        strike_rate.append(strike_rate_value)

    # Create a Pandas DataFrame
    data = {
        'Player': player_names,
        'Mat': matches,
        'Inns': innings,
        'Balls': balls,
        'Overs': overs,
        'Mdns': maidens,
        'Runs': runs,
        'Wkts': wickets,
        'BBI': bbi,
        'Ave': average,
        'Econ': economy,
        'SR': strike_rate,
    }
    df_bowling_stats = pd.DataFrame(data)

    # Display the DataFrame
    print(df_bowling_stats)
else:
    print("Table not found on the webpage.")

                       Player  Mat  Inns  Balls  Overs  Mdns  Runs  Wkts  \
0               A Zampa (AUS)    9     9    474   79.0   1.0   416    22
1           D Madushanka (SL)    9     9    470   78.2   4.0   525    21
2              G Coetzee (SA)    7     7    327   54.3   1.0   349    18
3   Shaheen Shah Afridi (PAK)    9     9    486   81.0   3.0   481    18
4             JJ Bumrah (IND)    9     9    437   72.5   6.0   266    17
..                        ...  ...   ...    ...    ...   ...   ...   ...
77              V Kohli (IND)    9     2     21    3.3   NaN    15     1
78             R Ashwin (IND)    1     1     60   10.0   1.0    34     1
79        AL Phehlukwayo (SA)    1     1     42    7.0   NaN    36     1
80       Saqib Zulfiqar (NED)    2     2     30    5.0   NaN    40     1
81              JE Root (ENG)    9     2     61   10.1   NaN    67     1

     BBI    Ave  Econ     SR
0    4/8  18.90  5.26  21.54
1   5/80  25.00  6.70  22.38
2   4/44  19.38  6.40  18.16
3   5/54  26.72  5.93  27.00
4   4/39  15.64  3.65  25.70
..   ...    ...   ...    ...
77  1/13  15.00  4.28  21.00
78  1/34  34.00  3.40  60.00
79  1/36  36.00  5.14  42.00
80  1/25  40.00  8.00  30.00
81  1/19  67.00  6.59  61.00

[82 rows x 12 columns]

In [ ]:
df_bowling_stats.head()

,Player,Mat,Inns,Balls,Overs,Mdns,Runs,Wkts,BBI,Ave,Econ,SR
0,A Zampa (AUS),9,9,474,79.0,1.0,416,22,4/8,18.90,5.26,21.54
1,D Madushanka (SL),9,9,470,78.2,4.0,525,21,5/80,25.00,6.70,22.38
2,G Coetzee (SA),7,7,327,54.3,1.0,349,18,4/44,19.38,6.40,18.16
3,Shaheen Shah Afridi (PAK),9,9,486,81.0,3.0,481,18,5/54,26.72,5.93,27.00
4,JJ Bumrah (IND),9,9,437,72.5,6.0,266,17,4/39,15.64,3.65,25.70

In [ ]:
df_bowling_stats.tail()

,Player,Mat,Inns,Balls,Overs,Mdns,Runs,Wkts,BBI,Ave,Econ,SR
77,V Kohli (IND),9,2,21,3.3,NaN,15,1,1/13,15.0,4.28,21.0
78,R Ashwin (IND),1,1,60,10.0,1.0,34,1,1/34,34.0,3.40,60.0
79,AL Phehlukwayo (SA),1,1,42,7.0,NaN,36,1,1/36,36.0,5.14,42.0
80,Saqib Zulfiqar (NED),2,2,30,5.0,NaN,40,1,1/25,40.0,8.00,30.0
81,JE Root (ENG),9,2,61,10.1,NaN,67,1,1/19,67.0,6.59,61.0

In [ ]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.espncricinfo.com/records/tournament/bowling-most-wickets-career/icc-cricket-world-cup-2023-24-15338"

response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

# Find the table containing the most wickets data
table = soup.find('table', class_='ds-table-xs')  # Update the class name based on the actual class of the table
if table:
    # Initialize lists to store data
    player_names = []
    team_names = []
    matches = []
    innings = []
    balls = []
    overs = []
    maidens = []
    runs = []
    wickets = []
    bbi = []
    average = []
    economy = []
    strike_rate = []

    # Extract data from the table
    for row in table.find('tbody').find_all('tr'):
        columns = row.find_all('td')
        player_and_team_name = columns[0].text.strip()

        # Extracting player name and team name
        player_name, team_name_in_brackets = map(str.strip, player_and_team_name.split('('))

        # Removing round brackets from team name
        team_name = team_name_in_brackets.rstrip(')')

        match = int(columns[2].text.strip())
        inning = int(columns[3].text.strip())
        ball = int(columns[4].text.strip())
        over = float(columns[5].text.strip())
        maiden = None if columns[6].text.strip() == '-' else int(columns[6].text.strip())
        run = int(columns[7].text.strip())
        wicket = int(columns[8].text.strip())
        bbi_value = columns[9].text.strip()
        average_value = float(columns[10].text.strip())
        economy_value = float(columns[11].text.strip())
        strike_rate_value = float(columns[12].text.strip())

        player_names.append(player_name)
        team_names.append(team_name)
        matches.append(match)
        innings.append(inning)
        balls.append(ball)
        overs.append(over)
        maidens.append(maiden)
        runs.append(run)
        wickets.append(wicket)
        bbi.append(bbi_value)
        average.append(average_value)
        economy.append(economy_value)
        strike_rate.append(strike_rate_value)

    # Create a Pandas DataFrame
    data = {
        'Player': player_names,
        'Team': team_names,
        'Mat': matches,
        'Inns': innings,
        'Balls': balls,
        'Overs': overs,
        'Mdns': maidens,
        'Runs': runs,
        'Wkts': wickets,
        'BBI': bbi,
        'Ave': average,
        'Econ': economy,
        'SR': strike_rate,
    }
    df_bowling_stats = pd.DataFrame(data)

    # Display the DataFrame
    print(df_bowling_stats)
else:
    print("Table not found on the webpage.")

                 Player Team  Mat  Inns  Balls  Overs  Mdns  Runs  Wkts   BBI  \
0               A Zampa  AUS    9     9    474   79.0   1.0   416    22   4/8
1          D Madushanka   SL    9     9    470   78.2   4.0   525    21  5/80
2             G Coetzee   SA    7     7    327   54.3   1.0   349    18  4/44
3   Shaheen Shah Afridi  PAK    9     9    486   81.0   3.0   481    18  5/54
4             JJ Bumrah  IND    9     9    437   72.5   6.0   266    17  4/39
..                  ...  ...  ...   ...    ...    ...   ...   ...   ...   ...
77              V Kohli  IND    9     2     21    3.3   NaN    15     1  1/13
78             R Ashwin  IND    1     1     60   10.0   1.0    34     1  1/34
79       AL Phehlukwayo   SA    1     1     42    7.0   NaN    36     1  1/36
80       Saqib Zulfiqar  NED    2     2     30    5.0   NaN    40     1  1/25
81              JE Root  ENG    9     2     61   10.1   NaN    67     1  1/19

      Ave  Econ     SR
0   18.90  5.26  21.54
1   25.00  6.70  22.38
2   19.38  6.40  18.16
3   26.72  5.93  27.00
4   15.64  3.65  25.70
..    ...   ...    ...
77  15.00  4.28  21.00
78  34.00  3.40  60.00
79  36.00  5.14  42.00
80  40.00  8.00  30.00
81  67.00  6.59  61.00

[82 rows x 13 columns]

In [ ]:
df_bowling_stats.head()

,Player,Team,Mat,Inns,Balls,Overs,Mdns,Runs,Wkts,BBI,Ave,Econ,SR
0,A Zampa,AUS,9,9,474,79.0,1.0,416,22,4/8,18.90,5.26,21.54
1,D Madushanka,SL,9,9,470,78.2,4.0,525,21,5/80,25.00,6.70,22.38
2,G Coetzee,SA,7,7,327,54.3,1.0,349,18,4/44,19.38,6.40,18.16
3,Shaheen Shah Afridi,PAK,9,9,486,81.0,3.0,481,18,5/54,26.72,5.93,27.00
4,JJ Bumrah,IND,9,9,437,72.5,6.0,266,17,4/39,15.64,3.65,25.70

In [ ]:
# List of semifinal teams
semifinal_teams = ['IND', 'AUS', 'SA', 'NZ']

# Filter DataFrame based on semifinal teams
df_semifinal_players = df_bowling_stats[df_bowling_stats['Team'].isin(semifinal_teams)]

# Display the filtered DataFrame
print(df_semifinal_players)

            Player Team  Mat  Inns  Balls  Overs  Mdns  Runs  Wkts   BBI  \
0          A Zampa  AUS    9     9    474   79.0   1.0   416    22   4/8
2        G Coetzee   SA    7     7    327   54.3   1.0   349    18  4/44
4        JJ Bumrah  IND    9     9    437   72.5   6.0   266    17  4/39
5         M Jansen   SA    8     8    388   64.4   3.0   415    17  3/31
6   Mohammed Shami  IND    5     5    192   32.0   3.0   153    16  5/18
7        RA Jadeja  IND    9     9    441   73.3   4.0   292    16  5/33
8       MJ Santner   NZ    9     9    496   82.4   3.0   398    16  5/59
12   Kuldeep Yadav  IND    9     9    451   75.1   2.0   312    14   2/7
13      KA Maharaj   SA    9     9    474   79.0   1.0   346    14  4/46
14        TA Boult   NZ    9     9    486   81.0   6.0   418    13  3/37
15        K Rabada   SA    8     8    401   66.5   7.0   323    12  3/33
16  Mohammed Siraj  IND    9     9    399   66.3   6.0   346    12  3/16
17    JR Hazlewood  AUS    9     9    451   75.1   5.0   377    12  3/38
21        MJ Henry   NZ    7     7    326   54.2   3.0   315    11  3/40
24     LH Ferguson   NZ    6     6    276   46.0   3.0   236    10  3/19
26         L Ngidi   SA    8     8    363   60.3   6.0   355    10  2/26
30      PJ Cummins  AUS    9     9    419   69.5   1.0   430    10  2/32
31        MA Starc  AUS    8     8    402   67.0   1.0   439    10  2/43
39        T Shamsi   SA    3     3    167   27.5   NaN   170     7  4/60
43     GD Phillips   NZ    9     9    210   35.0   1.0   200     6  3/37
48       HH Pandya  IND    4     4     99   16.3   NaN   113     5  2/34
52      GJ Maxwell  AUS    7     6    315   52.3   1.0   260     5  2/34
54      R Ravindra   NZ    9     8    352   58.4   NaN   333     5  2/21
56      MP Stoinis  AUS    6     6    114   19.0   NaN   143     4  2/40
58      TG Southee   NZ    3     3    138   23.0   NaN   156     4  2/77
65     LB Williams   SA    1     1     52    8.4   1.0    56     2  2/56
66       SA Abbott  AUS    1     1     60   10.0   NaN    61     2  2/61
67        MR Marsh  AUS    8     4     66   11.0   NaN    91     2  2/19
68       SN Thakur  IND    3     3    102   17.0   NaN   102     2  1/31
70     JDS Neesham   NZ    3     3     87   14.3   NaN   157     2  1/32
76       RG Sharma  IND    9     1      5    0.5   NaN     7     1   1/7
77         V Kohli  IND    9     2     21    3.3   NaN    15     1  1/13
78        R Ashwin  IND    1     1     60   10.0   1.0    34     1  1/34
79  AL Phehlukwayo   SA    1     1     42    7.0   NaN    36     1  1/36

      Ave   Econ     SR
0   18.90   5.26  21.54
2   19.38   6.40  18.16
4   15.64   3.65  25.70
5   24.41   6.41  22.82
6    9.56   4.78  12.00
7   18.25   3.97  27.56
8   24.87   4.81  31.00
12  22.28   4.15  32.21
13  24.71   4.37  33.85
14  32.15   5.16  37.38
15  26.91   4.83  33.41
16  28.83   5.20  33.25
17  31.41   5.01  37.58
21  28.63   5.79  29.63
24  23.60   5.13  27.60
26  35.50   5.86  36.30
30  43.00   6.15  41.90
31  43.90   6.55  40.20
39  24.28   6.10  23.85
43  33.33   5.71  35.00
48  22.60   6.84  19.80
52  52.00   4.95  63.00
54  66.60   5.67  70.40
56  35.75   7.52  28.50
58  39.00   6.78  34.50
65  28.00   6.46  26.00
66  30.50   6.10  30.00
67  45.50   8.27  33.00
68  51.00   6.00  51.00
70  78.50  10.82  43.50
76   7.00   8.40   5.00
77  15.00   4.28  21.00
78  34.00   3.40  60.00
79  36.00   5.14  42.00

In [ ]:
# Save the filtered DataFrame to a CSV file
df_semifinal_players.to_csv('semifinal_players_1.csv', index=False)

***BOWLING STATS WITHOUT HAVING ANY FILTER***

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.espncricinfo.com/records/tournament/bowling-most-wickets-career/icc-cricket-world-cup-2023-24-15338"

response = requests.get(url)
soup = BeautifulSoup(response.text, 'html.parser')

# Find the table containing the most wickets data
table = soup.find('table', class_='ds-table-xs')  # Update the class name based on the actual class of the table
if table:
    # Initialize lists to store data
    player_names = []
    team_names = []
    matches = []
    innings = []
    balls = []
    overs = []
    maidens = []
    runs = []
    wickets = []
    average = []
    economy = []
    strike_rate = []

    # Extract data from the table
    for row in table.find('tbody').find_all('tr'):
        columns = row.find_all('td')
        player_and_team_name = columns[0].text.strip()

        # Extracting player name and team name
        player_name, team_name_in_brackets = map(str.strip, player_and_team_name.split('('))

        # Removing round brackets from team name
        team_name = team_name_in_brackets.rstrip(')')

        match = int(columns[2].text.strip())
        inning = int(columns[3].text.strip())
        ball = int(columns[4].text.strip())
        over = float(columns[5].text.strip())
        maiden = None if columns[6].text.strip() == '-' else int(columns[6].text.strip())
        run = int(columns[7].text.strip())
        wicket = int(columns[8].text.strip())
        average_value = float(columns[10].text.strip())
        economy_value = float(columns[11].text.strip())
        strike_rate_value = float(columns[12].text.strip())

        player_names.append(player_name)
        team_names.append(team_name)
        matches.append(match)
        innings.append(inning)
        balls.append(ball)
        overs.append(over)
        maidens.append(maiden)
        runs.append(run)
        wickets.append(wicket)
        average.append(average_value)
        economy.append(economy_value)
        strike_rate.append(strike_rate_value)

    # Create a Pandas DataFrame
    data = {
        'Player': player_names,
        'Team': team_names,
        'Mat': matches,
        'Inns': innings,
        'Balls': balls,
        'Overs': overs,
        'Mdns': maidens,
        'Runs': runs,
        'Wkts': wickets,
        'Ave': average,
        'Econ': economy,
        'SR': strike_rate,
    }
    df_bowling_stats = pd.DataFrame(data)

    # Display the DataFrame
    print(df_bowling_stats)
else:
    print("Table not found on the webpage.")

                 Player Team  Mat  Inns  Balls  Overs  Mdns  Runs  Wkts  \
0               A Zampa  AUS    9     9    474   79.0   1.0   416    22
1          D Madushanka   SL    9     9    470   78.2   4.0   525    21
2             G Coetzee   SA    7     7    327   54.3   1.0   349    18
3   Shaheen Shah Afridi  PAK    9     9    486   81.0   3.0   481    18
4             JJ Bumrah  IND    9     9    437   72.5   6.0   266    17
..                  ...  ...  ...   ...    ...    ...   ...   ...   ...
77              V Kohli  IND    9     2     21    3.3   NaN    15     1
78             R Ashwin  IND    1     1     60   10.0   1.0    34     1
79       AL Phehlukwayo   SA    1     1     42    7.0   NaN    36     1
80       Saqib Zulfiqar  NED    2     2     30    5.0   NaN    40     1
81              JE Root  ENG    9     2     61   10.1   NaN    67     1

      Ave  Econ     SR
0   18.90  5.26  21.54
1   25.00  6.70  22.38
2   19.38  6.40  18.16
3   26.72  5.93  27.00
4   15.64  3.65  25.70
..    ...   ...    ...
77  15.00  4.28  21.00
78  34.00  3.40  60.00
79  36.00  5.14  42.00
80  40.00  8.00  30.00
81  67.00  6.59  61.00

[82 rows x 12 columns]

In [3]:
# Create a copy of the DataFrame
df_semifinal_player_copy = df_bowling_stats.copy()

# Fill missing values in the 'Mdns' column with 0
df_semifinal_player_copy['Mdns'].fillna(0, inplace=True)

In [4]:
df_semifinal_player_copy.head()

,Player,Team,Mat,Inns,Balls,Overs,Mdns,Runs,Wkts,Ave,Econ,SR
0,A Zampa,AUS,9,9,474,79.0,1.0,416,22,18.90,5.26,21.54
1,D Madushanka,SL,9,9,470,78.2,4.0,525,21,25.00,6.70,22.38
2,G Coetzee,SA,7,7,327,54.3,1.0,349,18,19.38,6.40,18.16
3,Shaheen Shah Afridi,PAK,9,9,486,81.0,3.0,481,18,26.72,5.93,27.00
4,JJ Bumrah,IND,9,9,437,72.5,6.0,266,17,15.64,3.65,25.70

In [5]:
df_semifinal_player_copy.tail()

,Player,Team,Mat,Inns,Balls,Overs,Mdns,Runs,Wkts,Ave,Econ,SR
77,V Kohli,IND,9,2,21,3.3,0.0,15,1,15.0,4.28,21.0
78,R Ashwin,IND,1,1,60,10.0,1.0,34,1,34.0,3.40,60.0
79,AL Phehlukwayo,SA,1,1,42,7.0,0.0,36,1,36.0,5.14,42.0
80,Saqib Zulfiqar,NED,2,2,30,5.0,0.0,40,1,40.0,8.00,30.0
81,JE Root,ENG,9,2,61,10.1,0.0,67,1,67.0,6.59,61.0

***ANN MODEL ON THE WHOLE DATA***

In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

# Function to preprocess the data and create the model
def preprocess_and_create_model(df):
    # Extract features and target variable
    X = df[['Mat', 'Inns', 'Balls', 'Overs', 'Mdns', 'Runs', 'Ave', 'Econ', 'SR']]
    y = df['Wkts']

    # print(X)
    # Split the data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Standardize/Normalize features
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    # Build the ANN model
    model = tf.keras.Sequential([
        tf.keras.layers.Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(1, activation='linear')  # For regression task
    ])

    # Compile the model
    model.compile(optimizer='adam', loss='mean_squared_error')

    # Train the model
    model.fit(X_train, y_train, epochs=50, batch_size=32, validation_data=(X_test, y_test))

    return model, scaler


# Preprocess the data and create the model
model, scaler = preprocess_and_create_model(df_semifinal_player_copy)

# # Assuming upcoming_matches_data is your DataFrame for the upcoming matches
upcoming_matches_X = df_semifinal_player_copy[['Mat', 'Inns', 'Balls', 'Overs', 'Mdns', 'Runs', 'Ave', 'Econ', 'SR']]
upcoming_matches_X_scaled = scaler.transform(upcoming_matches_X)

# Make predictions for the upcoming matches dataset
upcoming_matches_predictions = model.predict(upcoming_matches_X_scaled)

# Identify the player with the highest predicted wickets
best_player = df_bowling_stats.iloc[upcoming_matches_predictions.argmax()]

# Print the details of the best player
print("Best Player in Upcoming Matches:")
print("Player:", best_player['Player'])
print("Team:", best_player['Team'])

Epoch 1/50
3/3 [==============================] - 1s 76ms/step - loss: 82.7465 - val_loss: 115.5417
Epoch 2/50
3/3 [==============================] - 0s 16ms/step - loss: 78.3807 - val_loss: 109.8662
Epoch 3/50
3/3 [==============================] - 0s 16ms/step - loss: 74.5376 - val_loss: 104.1088
Epoch 4/50
3/3 [==============================] - 0s 17ms/step - loss: 70.6876 - val_loss: 98.1724
Epoch 5/50
3/3 [==============================] - 0s 16ms/step - loss: 67.1288 - val_loss: 91.9696
Epoch 6/50
3/3 [==============================] - 0s 17ms/step - loss: 63.3049 - val_loss: 85.3938
Epoch 7/50
3/3 [==============================] - 0s 20ms/step - loss: 59.0948 - val_loss: 78.5378
Epoch 8/50
3/3 [==============================] - 0s 17ms/step - loss: 54.8453 - val_loss: 71.1840
Epoch 9/50
3/3 [==============================] - 0s 16ms/step - loss: 50.2067 - val_loss: 63.3668
Epoch 10/50
3/3 [==============================] - 0s 16ms/step - loss: 45.4937 - val_loss: 55.3300
Epoch 11/50
3/3 [==============================] - 0s 16ms/step - loss: 40.6714 - val_loss: 47.2927
Epoch 12/50
3/3 [==============================] - 0s 16ms/step - loss: 35.7783 - val_loss: 39.1158
Epoch 13/50
3/3 [==============================] - 0s 20ms/step - loss: 30.6541 - val_loss: 31.7933
Epoch 14/50
3/3 [==============================] - 0s 16ms/step - loss: 26.2655 - val_loss: 24.8514
Epoch 15/50
3/3 [==============================] - 0s 16ms/step - loss: 21.9295 - val_loss: 18.4058
Epoch 16/50
3/3 [==============================] - 0s 16ms/step - loss: 17.6870 - val_loss: 13.2780
Epoch 17/50
3/3 [==============================] - 0s 17ms/step - loss: 14.4273 - val_loss: 9.3568
Epoch 18/50
3/3 [==============================] - 0s 18ms/step - loss: 11.7749 - val_loss: 6.6605
Epoch 19/50
3/3 [==============================] - 0s 16ms/step - loss: 9.9456 - val_loss: 5.0501
Epoch 20/50
3/3 [==============================] - 0s 17ms/step - loss: 8.6751 - val_loss: 4.3557
Epoch 21/50
3/3 [==============================] - 0s 16ms/step - loss: 7.9301 - val_loss: 4.1445
Epoch 22/50
3/3 [==============================] - 0s 16ms/step - loss: 7.5719 - val_loss: 4.2769
Epoch 23/50
3/3 [==============================] - 0s 18ms/step - loss: 7.2124 - val_loss: 4.5699
Epoch 24/50
3/3 [==============================] - 0s 27ms/step - loss: 7.0292 - val_loss: 4.7250
Epoch 25/50
3/3 [==============================] - 0s 15ms/step - loss: 6.9083 - val_loss: 4.5600
Epoch 26/50
3/3 [==============================] - 0s 16ms/step - loss: 6.5713 - val_loss: 4.2181
Epoch 27/50
3/3 [==============================] - 0s 16ms/step - loss: 6.2204 - val_loss: 3.9291
Epoch 28/50
3/3 [==============================] - 0s 17ms/step - loss: 5.9074 - val_loss: 3.6553
Epoch 29/50
3/3 [==============================] - 0s 18ms/step - loss: 5.5746 - val_loss: 3.4507
Epoch 30/50
3/3 [==============================] - 0s 21ms/step - loss: 5.2822 - val_loss: 3.3105
Epoch 31/50
3/3 [==============================] - 0s 19ms/step - loss: 5.0407 - val_loss: 3.1853
Epoch 32/50
3/3 [==============================] - 0s 16ms/step - loss: 4.7916 - val_loss: 3.0970
Epoch 33/50
3/3 [==============================] - 0s 16ms/step - loss: 4.5200 - val_loss: 3.0104
Epoch 34/50
3/3 [==============================] - 0s 16ms/step - loss: 4.2854 - val_loss: 2.8463
Epoch 35/50
3/3 [==============================] - 0s 16ms/step - loss: 4.0645 - val_loss: 2.6231
Epoch 36/50
3/3 [==============================] - 0s 16ms/step - loss: 3.8446 - val_loss: 2.4933
Epoch 37/50
3/3 [==============================] - 0s 16ms/step - loss: 3.6977 - val_loss: 2.4079
Epoch 38/50
3/3 [==============================] - 0s 19ms/step - loss: 3.5283 - val_loss: 2.3766
Epoch 39/50
3/3 [==============================] - 0s 17ms/step - loss: 3.3558 - val_loss: 2.3876
Epoch 40/50
3/3 [==============================] - 0s 17ms/step - loss: 3.2110 - val_loss: 2.4354
Epoch 41/50
3/3 [==============================] - 0s 17ms/step - loss: 3.0557 - val_loss: 2.5123
Epoch 42/50
3/3 [==============================] - 0s 17ms/step - loss: 2.9153 - val_loss: 2.5394
Epoch 43/50
3/3 [==============================] - 0s 18ms/step - loss: 2.8127 - val_loss: 2.4611
Epoch 44/50
3/3 [==============================] - 0s 17ms/step - loss: 2.7265 - val_loss: 2.4008
Epoch 45/50
3/3 [==============================] - 0s 16ms/step - loss: 2.6392 - val_loss: 2.3668
Epoch 46/50
3/3 [==============================] - 0s 16ms/step - loss: 2.5524 - val_loss: 2.3462
Epoch 47/50
3/3 [==============================] - 0s 18ms/step - loss: 2.4762 - val_loss: 2.3143
Epoch 48/50
3/3 [==============================] - 0s 17ms/step - loss: 2.3750 - val_loss: 2.3914
Epoch 49/50
3/3 [==============================] - 0s 16ms/step - loss: 2.2661 - val_loss: 2.6859
Epoch 50/50
3/3 [==============================] - 0s 17ms/step - loss: 2.2011 - val_loss: 2.7981
3/3 [==============================] - 0s 4ms/step
Best Player in Upcoming Matches:
Player: D Madushanka
Team: SL

***DATAFRAME OF THE FILTERED DATA***

In [12]:
# List of semifinal teams
semifinal_teams = ['IND', 'AUS', 'SA', 'NZ']

# Filter DataFrame based on semifinal teams
df_semifinal_player = df_bowling_stats[df_bowling_stats['Team'].isin(semifinal_teams)]

# Display the filtered DataFrame
print(df_semifinal_player)

            Player Team  Mat  Inns  Balls  Overs  Mdns  Runs  Wkts    Ave  \
0          A Zampa  AUS    9     9    474   79.0   1.0   416    22  18.90
2        G Coetzee   SA    7     7    327   54.3   1.0   349    18  19.38
4        JJ Bumrah  IND    9     9    437   72.5   6.0   266    17  15.64
5         M Jansen   SA    8     8    388   64.4   3.0   415    17  24.41
6   Mohammed Shami  IND    5     5    192   32.0   3.0   153    16   9.56
7        RA Jadeja  IND    9     9    441   73.3   4.0   292    16  18.25
8       MJ Santner   NZ    9     9    496   82.4   3.0   398    16  24.87
12   Kuldeep Yadav  IND    9     9    451   75.1   2.0   312    14  22.28
13      KA Maharaj   SA    9     9    474   79.0   1.0   346    14  24.71
14        TA Boult   NZ    9     9    486   81.0   6.0   418    13  32.15
15        K Rabada   SA    8     8    401   66.5   7.0   323    12  26.91
16  Mohammed Siraj  IND    9     9    399   66.3   6.0   346    12  28.83
17    JR Hazlewood  AUS    9     9    451   75.1   5.0   377    12  31.41
21        MJ Henry   NZ    7     7    326   54.2   3.0   315    11  28.63
24     LH Ferguson   NZ    6     6    276   46.0   3.0   236    10  23.60
26         L Ngidi   SA    8     8    363   60.3   6.0   355    10  35.50
30      PJ Cummins  AUS    9     9    419   69.5   1.0   430    10  43.00
31        MA Starc  AUS    8     8    402   67.0   1.0   439    10  43.90
39        T Shamsi   SA    3     3    167   27.5   NaN   170     7  24.28
43     GD Phillips   NZ    9     9    210   35.0   1.0   200     6  33.33
48       HH Pandya  IND    4     4     99   16.3   NaN   113     5  22.60
52      GJ Maxwell  AUS    7     6    315   52.3   1.0   260     5  52.00
54      R Ravindra   NZ    9     8    352   58.4   NaN   333     5  66.60
56      MP Stoinis  AUS    6     6    114   19.0   NaN   143     4  35.75
58      TG Southee   NZ    3     3    138   23.0   NaN   156     4  39.00
65     LB Williams   SA    1     1     52    8.4   1.0    56     2  28.00
66       SA Abbott  AUS    1     1     60   10.0   NaN    61     2  30.50
67        MR Marsh  AUS    8     4     66   11.0   NaN    91     2  45.50
68       SN Thakur  IND    3     3    102   17.0   NaN   102     2  51.00
70     JDS Neesham   NZ    3     3     87   14.3   NaN   157     2  78.50
76       RG Sharma  IND    9     1      5    0.5   NaN     7     1   7.00
77         V Kohli  IND    9     2     21    3.3   NaN    15     1  15.00
78        R Ashwin  IND    1     1     60   10.0   1.0    34     1  34.00
79  AL Phehlukwayo   SA    1     1     42    7.0   NaN    36     1  36.00

     Econ     SR
0    5.26  21.54
2    6.40  18.16
4    3.65  25.70
5    6.41  22.82
6    4.78  12.00
7    3.97  27.56
8    4.81  31.00
12   4.15  32.21
13   4.37  33.85
14   5.16  37.38
15   4.83  33.41
16   5.20  33.25
17   5.01  37.58
21   5.79  29.63
24   5.13  27.60
26   5.86  36.30
30   6.15  41.90
31   6.55  40.20
39   6.10  23.85
43   5.71  35.00
48   6.84  19.80
52   4.95  63.00
54   5.67  70.40
56   7.52  28.50
58   6.78  34.50
65   6.46  26.00
66   6.10  30.00
67   8.27  33.00
68   6.00  51.00
70  10.82  43.50
76   8.40   5.00
77   4.28  21.00
78   3.40  60.00
79   5.14  42.00

In [13]:
# Create a copy of the DataFrame
df_semifinal_players_copy = df_semifinal_player.copy()

# Fill missing values in the 'Mdns' column with 0
df_semifinal_players_copy['Mdns'].fillna(0, inplace=True)

In [14]:
df_semifinal_players_copy.head()

,Player,Team,Mat,Inns,Balls,Overs,Mdns,Runs,Wkts,Ave,Econ,SR
0,A Zampa,AUS,9,9,474,79.0,1.0,416,22,18.90,5.26,21.54
2,G Coetzee,SA,7,7,327,54.3,1.0,349,18,19.38,6.40,18.16
4,JJ Bumrah,IND,9,9,437,72.5,6.0,266,17,15.64,3.65,25.70
5,M Jansen,SA,8,8,388,64.4,3.0,415,17,24.41,6.41,22.82
6,Mohammed Shami,IND,5,5,192,32.0,3.0,153,16,9.56,4.78,12.00

In [15]:
df_semifinal_players_copy.tail()

,Player,Team,Mat,Inns,Balls,Overs,Mdns,Runs,Wkts,Ave,Econ,SR
70,JDS Neesham,NZ,3,3,87,14.3,0.0,157,2,78.5,10.82,43.5
76,RG Sharma,IND,9,1,5,0.5,0.0,7,1,7.0,8.40,5.0
77,V Kohli,IND,9,2,21,3.3,0.0,15,1,15.0,4.28,21.0
78,R Ashwin,IND,1,1,60,10.0,1.0,34,1,34.0,3.40,60.0
79,AL Phehlukwayo,SA,1,1,42,7.0,0.0,36,1,36.0,5.14,42.0

In [16]:
df_semifinal_players_copy.to_csv('bowling_stat_final.csv', index=False)

In [17]:
df_semifinal_players_copy.columns

Index(['Player', 'Team', 'Mat', 'Inns', 'Balls', 'Overs', 'Mdns', 'Runs',
       'Wkts', 'Ave', 'Econ', 'SR'],
      dtype='object')

***ANN MODEL FOR THE FILTERED DATA HAVING TEAMS***

***IND, AUS, NZ, SA***

In [19]:
# Assuming df_semifinal_player_copy is your DataFrame

# Extract features and target variable
X = df_semifinal_players_copy[['Mat', 'Inns', 'Balls', 'Overs', 'Mdns', 'Runs', 'Ave', 'Econ', 'SR']]
y = df_semifinal_players_copy['Wkts']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Standardize/Normalize features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Build the ANN model
model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(1, activation='linear')  # For regression task
])

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Train the model
model.fit(X_train_scaled, y_train, epochs=50, batch_size=32, validation_data=(X_test_scaled, y_test))

# Evaluate the model on the testing set
loss = model.evaluate(X_test_scaled, y_test)
print(f'Mean Squared Error on Test Set: {loss}')

# Assuming semifinals_data is your DataFrame for the semi-finals
semifinals_X = df_semifinal_players_copy[['Mat', 'Inns', 'Balls', 'Overs', 'Mdns', 'Runs', 'Ave', 'Econ', 'SR']]
semifinals_X_scaled = scaler.transform(semifinals_X)

# Make predictions for the semi-finals dataset
semifinals_predictions = model.predict(semifinals_X_scaled)
print(semifinals_predictions)

Epoch 1/50
1/1 [==============================] - 3s 3s/step - loss: 134.7044 - val_loss: 54.3662
Epoch 2/50
1/1 [==============================] - 0s 53ms/step - loss: 132.1331 - val_loss: 53.0739
Epoch 3/50
1/1 [==============================] - 0s 36ms/step - loss: 129.6766 - val_loss: 51.7911
Epoch 4/50
1/1 [==============================] - 0s 33ms/step - loss: 127.2982 - val_loss: 50.5638
Epoch 5/50
1/1 [==============================] - 0s 35ms/step - loss: 124.9796 - val_loss: 49.3923
Epoch 6/50
1/1 [==============================] - 0s 36ms/step - loss: 122.7437 - val_loss: 48.2448
Epoch 7/50
1/1 [==============================] - 0s 34ms/step - loss: 120.5367 - val_loss: 47.0951
Epoch 8/50
1/1 [==============================] - 0s 36ms/step - loss: 118.3461 - val_loss: 45.9678
Epoch 9/50
1/1 [==============================] - 0s 39ms/step - loss: 116.2008 - val_loss: 44.8681
Epoch 10/50
1/1 [==============================] - 0s 40ms/step - loss: 114.0976 - val_loss: 43.7868
Epoch 11/50
1/1 [==============================] - 0s 42ms/step - loss: 112.0231 - val_loss: 42.7186
Epoch 12/50
1/1 [==============================] - 0s 38ms/step - loss: 109.9486 - val_loss: 41.6535
Epoch 13/50
1/1 [==============================] - 0s 37ms/step - loss: 107.8661 - val_loss: 40.5920
Epoch 14/50
1/1 [==============================] - 0s 36ms/step - loss: 105.7724 - val_loss: 39.5363
Epoch 15/50
1/1 [==============================] - 0s 43ms/step - loss: 103.6749 - val_loss: 38.4963
Epoch 16/50
1/1 [==============================] - 0s 48ms/step - loss: 101.5351 - val_loss: 37.4639
Epoch 17/50
1/1 [==============================] - 0s 43ms/step - loss: 99.3615 - val_loss: 36.4223
Epoch 18/50
1/1 [==============================] - 0s 40ms/step - loss: 97.1894 - val_loss: 35.3826
Epoch 19/50
1/1 [==============================] - 0s 41ms/step - loss: 94.9994 - val_loss: 34.3399
Epoch 20/50
1/1 [==============================] - 0s 58ms/step - loss: 92.7967 - val_loss: 33.2953
Epoch 21/50
1/1 [==============================] - 0s 34ms/step - loss: 90.5955 - val_loss: 32.2483
Epoch 22/50
1/1 [==============================] - 0s 39ms/step - loss: 88.3920 - val_loss: 31.1991
Epoch 23/50
1/1 [==============================] - 0s 39ms/step - loss: 86.1713 - val_loss: 30.1460
Epoch 24/50
1/1 [==============================] - 0s 38ms/step - loss: 83.9284 - val_loss: 29.0919
Epoch 25/50
1/1 [==============================] - 0s 47ms/step - loss: 81.6549 - val_loss: 28.0429
Epoch 26/50
1/1 [==============================] - 0s 41ms/step - loss: 79.3526 - val_loss: 26.9925
Epoch 27/50
1/1 [==============================] - 0s 48ms/step - loss: 77.0308 - val_loss: 25.9348
Epoch 28/50
1/1 [==============================] - 0s 38ms/step - loss: 74.6863 - val_loss: 24.8746
Epoch 29/50
1/1 [==============================] - 0s 38ms/step - loss: 72.3159 - val_loss: 23.8150
Epoch 30/50
1/1 [==============================] - 0s 40ms/step - loss: 69.9160 - val_loss: 22.7562
Epoch 31/50
1/1 [==============================] - 0s 42ms/step - loss: 67.4837 - val_loss: 21.7005
Epoch 32/50
1/1 [==============================] - 0s 37ms/step - loss: 65.0265 - val_loss: 20.6469
Epoch 33/50
1/1 [==============================] - 0s 39ms/step - loss: 62.5546 - val_loss: 19.5964
Epoch 34/50
1/1 [==============================] - 0s 39ms/step - loss: 60.0691 - val_loss: 18.5504
Epoch 35/50
1/1 [==============================] - 0s 39ms/step - loss: 57.5726 - val_loss: 17.5089
Epoch 36/50
1/1 [==============================] - 0s 37ms/step - loss: 55.0641 - val_loss: 16.4764
Epoch 37/50
1/1 [==============================] - 0s 35ms/step - loss: 52.5506 - val_loss: 15.4610
Epoch 38/50
1/1 [==============================] - 0s 38ms/step - loss: 50.0400 - val_loss: 14.4594
Epoch 39/50
1/1 [==============================] - 0s 36ms/step - loss: 47.5408 - val_loss: 13.4727
Epoch 40/50
1/1 [==============================] - 0s 35ms/step - loss: 45.0555 - val_loss: 12.4964
Epoch 41/50
1/1 [==============================] - 0s 34ms/step - loss: 42.5984 - val_loss: 11.5429
Epoch 42/50
1/1 [==============================] - 0s 44ms/step - loss: 40.1784 - val_loss: 10.6069
Epoch 43/50
1/1 [==============================] - 0s 36ms/step - loss: 37.7987 - val_loss: 9.7011
Epoch 44/50
1/1 [==============================] - 0s 37ms/step - loss: 35.4667 - val_loss: 8.8306
Epoch 45/50
1/1 [==============================] - 0s 35ms/step - loss: 33.2009 - val_loss: 7.9994
Epoch 46/50
1/1 [==============================] - 0s 37ms/step - loss: 31.0141 - val_loss: 7.2079
Epoch 47/50
1/1 [==============================] - 0s 35ms/step - loss: 28.9171 - val_loss: 6.4634
Epoch 48/50
1/1 [==============================] - 0s 34ms/step - loss: 26.9190 - val_loss: 5.7719
Epoch 49/50
1/1 [==============================] - 0s 39ms/step - loss: 25.0260 - val_loss: 5.1364
Epoch 50/50
1/1 [==============================] - 0s 37ms/step - loss: 23.2477 - val_loss: 4.5592
1/1 [==============================] - 0s 24ms/step - loss: 4.5592
Mean Squared Error on Test Set: 4.559202194213867
2/2 [==============================] - 0s 7ms/step
[[12.20564  ]
 [ 6.4845443]
 [14.497836 ]
 [ 8.758763 ]
 [ 6.271926 ]
 [12.517597 ]
 [12.475305 ]
 [10.7793   ]
 [10.71247  ]
 [12.921273 ]
 [11.220801 ]
 [10.849356 ]
 [11.186615 ]
 [ 4.772458 ]
 [ 3.7477462]
 [ 7.988967 ]
 [ 7.771078 ]
 [ 6.608447 ]
 [ 2.6480904]
 [ 2.7323058]
 [ 3.0389407]
 [ 3.592438 ]
 [ 5.7601924]
 [ 2.3970716]
 [ 2.0492508]
 [ 2.9684002]
 [ 2.7616532]
 [ 2.1330862]
 [ 1.8192141]
 [ 3.235584 ]
 [ 4.8027306]
 [ 3.6351724]
 [ 2.4962544]
 [ 2.3091707]]

***PREDICTING WHO WILL TAKE MOST WICKETS IN THE UPCOMING SEMI-FINAL MATCH BETWEEN IND VS NZ AND SA VS AUS***

In [20]:
# Assuming df_semifinal_player_copy is your DataFrame

# Filter players for 'IND' vs 'NZ' semi-final
ind_nz_players = df_semifinal_players_copy[df_semifinal_players_copy['Team'].isin(['IND', 'NZ'])]

# Extract features for the filtered players
ind_nz_X = ind_nz_players[['Mat', 'Inns', 'Balls', 'Overs', 'Mdns', 'Runs', 'Ave', 'Econ', 'SR']]
ind_nz_X_scaled = scaler.transform(ind_nz_X)

# Predict wickets for 'IND' vs 'NZ' players
ind_nz_predictions = model.predict(ind_nz_X_scaled)


# Identify the player with the highest predicted wickets
ind_nz_best_player = ind_nz_players.iloc[ind_nz_predictions.argmax()]

# Print the details of the best player
print("Best Player in IND vs NZ:")
print(ind_nz_best_player)


# Repeat the process for 'SA' vs 'AUS' semi-final
sa_aus_players = df_semifinal_players_copy[df_semifinal_players_copy['Team'].isin(['SA', 'AUS'])]
sa_aus_X = sa_aus_players[['Mat', 'Inns', 'Balls', 'Overs', 'Mdns', 'Runs', 'Ave', 'Econ', 'SR']]
sa_aus_X_scaled = scaler.transform(sa_aus_X)
sa_aus_predictions = model.predict(sa_aus_X_scaled)
sa_aus_best_player = sa_aus_players.loc[sa_aus_predictions.argmax()]

# Print the details of the best player
print("\nBest Player in SA vs AUS:")
print(sa_aus_best_player)

1/1 [==============================] - 0s 31ms/step
Best Player in IND vs NZ:
Player    JJ Bumrah
Team            IND
Mat               9
Inns              9
Balls           437
Overs          72.5
Mdns            6.0
Runs            266
Wkts             17
Ave           15.64
Econ           3.65
SR             25.7
Name: 4, dtype: object
1/1 [==============================] - 0s 30ms/step

Best Player in SA vs AUS:
Player    A Zampa
Team          AUS
Mat             9
Inns            9
Balls         474
Overs        79.0
Mdns          1.0
Runs          416
Wkts           22
Ave          18.9
Econ         5.26
SR          21.54
Name: 0, dtype: object

In [21]:
# Assuming df_semifinal_player_copy is your DataFrame

# Filter players for 'IND' vs 'NZ' semi-final
ind_nz_players = df_semifinal_players_copy[df_semifinal_players_copy['Team'].isin(['IND', 'NZ'])]

# Extract features for the filtered players
ind_nz_X = ind_nz_players[['Mat', 'Inns', 'Balls', 'Overs', 'Mdns', 'Runs', 'Ave', 'Econ', 'SR']]
ind_nz_X_scaled = scaler.transform(ind_nz_X)

# Predict wickets for 'IND' vs 'NZ' players
ind_nz_predictions = model.predict(ind_nz_X_scaled)

# Identify the player with the highest predicted wickets
ind_nz_best_player = ind_nz_players.iloc[ind_nz_predictions.argmax()]

# Print the name of the best player and the team name
print("Best Player in IND vs NZ who will most wickets:")
print("Player:", ind_nz_best_player['Player'])
print("Team:", ind_nz_best_player['Team'])


# Repeat the process for 'SA' vs 'AUS' semi-final
sa_aus_players = df_semifinal_players_copy[df_semifinal_players_copy['Team'].isin(['SA', 'AUS'])]
sa_aus_X = sa_aus_players[['Mat', 'Inns', 'Balls', 'Overs', 'Mdns', 'Runs', 'Ave', 'Econ', 'SR']]
sa_aus_X_scaled = scaler.transform(sa_aus_X)
sa_aus_predictions = model.predict(sa_aus_X_scaled)
sa_aus_best_player = sa_aus_players.iloc[sa_aus_predictions.argmax()]

# Print the name of the best player and the team name
print("\nBest Player in SA vs AUS who will most wickets:")
print("Player:", sa_aus_best_player['Player'])
print("Team:", sa_aus_best_player['Team'])

1/1 [==============================] - 0s 20ms/step
Best Player in IND vs NZ who will most wickets:
Player: JJ Bumrah
Team: IND
1/1 [==============================] - 0s 20ms/step

Best Player in SA vs AUS who will most wickets:
Player: A Zampa
Team: AUS